### PR TITLE
Fix to add path to listdir result

### PR DESCRIPTION
**Pull request by manabuishii**

### CODE REVIEW

**Comment by manabuishii** [comment]
I think this fix #42

**Comment by manabuishii** [comment]
```
ftp.nlst(path)
```
 returns just filenames.
So I add `path`

**Comment by kellrott** [comment]
At the moment, I don't have an environment with FTP servers to test this against. Have you tested this on your side?

**Comment by kellrott** [comment]
Tested on local system 👍

**Pull request merged**
